### ISSUE TITLE
The model is not being learned

### ISSUE THREAD

**Issue by H33J1N** [BarCodeReader/RCSB-PyTorch#7]
I trained the model with DUTS-TR dataset. 

At first, error was occurred because of different channel dimension (DUTS-TR: 1 channel), so I changed the code to eliminate rgb2gray code and started training.

However, learning goes saturated at the beginning. The best MAE is 0.11 of 2k step. The previous issue said that the model's converge speed is very fast, but the training results get higer MAE than 0.1

**Comment by BarCodeReader** [comment]
i think you are doing wrong...the input image is RGB and output result is a single-channel image.
the code and model are definitely working and you should check your data, not modifying our code and claim the result is not good.
you can download the dataset as links are provided, and follow the instruction to place your data under correct folder.

Hope this clarifies.

In addition, I attach a screenshot of freshly trained model today (you can see the date) using the current code in this repo, nothing is modified and i can get below result:
![image](https://user-images.githubusercontent.com/39732241/178651534-b103e4d9-ac53-4d85-876a-83547281916b.png)

cheers

**Comment by H33J1N** [comment]
Thanks for replying, The reason of code error is because of scikit-image version. After downgrade the version, the MAE scores are reduces to 0.048 at 1 epoch.
Thanks!
