### ISSUE TITLE
About predicted saliency maps of DUT-OMRON and DUTS-TE 

### ISSUE THREAD

**Issue by xuanli98** [BarCodeReader/RCSB-PyTorch#8]
Thanks for your great work. I downloaded the predicted saliency maps of your work. However, there are only 5162 predicted saliency maps in DUT-OMRON, instead of 5168. There are only 5018 predicted saliency maps in DUTS-TE, instead of 5019. Would you like to provide the full predicted saliency maps of DUT-OMRON and DUTS-TE. Thank you very much.

**Comment by BarCodeReader** [comment]
Hi,
Thanks for letting me know about this issue. Not sure how this happened, but I uploaded the full prediction, and you can get it via the link.

**Comment by xuanli98** [comment]
> Hi, Thanks for letting me know about this issue. Not sure how this happened, but I uploaded the full prediction, and you can get it via the link.

Thank you for your response! It seems that your provided new link doesn't contain the pretrained model.

**Comment by BarCodeReader** [comment]
should be fixed now

**Comment by xuanli98** [comment]
Thank you very much！
