### ISSUE TITLE
Question about starting

### ISSUE THREAD

**Issue by CptJaroSlav** [BarCodeReader/RCSB-PyTorch#9]
Hi,
I'm completely new but I want to learn something. I have question about what should i choose if I'm working on laptop with only GTX960M, what batchsize should i pick. Because i don't know how to move further. Thank you for your help.

![Zrzut ekranu 2023-05-30 130023](https://github.com/BarCodeReader/RCSB-PyTorch/assets/81368257/fc1d99dc-447a-4682-ba4e-b6ae151561ef)

**Comment by BarCodeReader** [comment]
in your terminal, "nvidia-smi" to check your GPU usage. Then you adjust batch size accordingly.
My suggestion is to play some easy repo, understand how everything works first~

cheers

**Comment by CptJaroSlav** [comment]
It seems to be 1, but it still stuck in the same place. If I dont figure it out I will go for easier
![S1](https://github.com/BarCodeReader/RCSB-PyTorch/assets/81368257/b0891923-8b1d-4b67-b802-28eb5b61f5c3)

**Comment by BarCodeReader** [comment]
2GB GPU RAM is definitely not enough.
https://github.com/BarCodeReader/RCSB-PyTorch#train--test
here I already indicate we need 24GB GPU RAM

**Comment by CptJaroSlav** [comment]
Last question is there anything think I could do to make it work beside new hardware? Thank u in advance

**Comment by BarCodeReader** [comment]
The code is verified to work, you can check those closed issues.
so I think after you fix the hardware, it should work.

cheers
